# Generated by Django 3.2.8 on 2021-11-01 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('customerAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.BigAutoField(primary_key=True, serialize=False)),
                ('serviceDate', models.DateTimeField(auto_now_add=True)),
                ('serviceAddress', models.CharField(max_length=200)),
                ('suspend', models.BooleanField(default=False)),
                ('suspendDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('customerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
    ]
