# Generated by Django 3.2.8 on 2021-11-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tierID', models.DecimalField(decimal_places=0, max_digits=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('rate', models.CharField(max_length=20)),
            ],
        ),
    ]
