# Generated by Django 3.2.8 on 2021-11-01 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billID', models.BigAutoField(primary_key=True, serialize=False)),
                ('amountDue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previousReading', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currentReading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('readingDate', models.DateTimeField()),
                ('lateFee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paidInFull', models.BooleanField()),
                ('accountID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.account')),
            ],
        ),
    ]
