# Generated by Django 3.2.8 on 2021-11-01 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211031_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fname',
        ),
    ]
