# Generated by Django 3.2.8 on 2021-11-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211031_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerAddress',
        ),
    ]
