# Generated by Django 3.2.8 on 2021-11-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211031_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='suspendDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(max_length=21),
        ),
    ]
