# Generated by Django 3.2.8 on 2021-11-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_therange_rate_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='theRange',
        ),
    ]
