# Generated by Django 3.2.8 on 2021-11-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20211101_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paidInFull',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='readingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
