# Generated by Django 3.2.8 on 2021-11-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_account_servicedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='currentReading',
            new_name='reading',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='previousReading',
        ),
    ]
