# Generated by Django 3.2.8 on 2021-11-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20211120_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='reading',
            new_name='currentReading',
        ),
    ]
