# Generated by Django 3.2.8 on 2021-11-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_reading_bill_currentreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='suspendDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
