# Generated by Django 3.2.8 on 2021-11-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_account_suspenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tierID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rate'),
        ),
        migrations.AlterField(
            model_name='account',
            name='suspendDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amountDue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paidInFull',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='readingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
