# Generated by Django 3.2.8 on 2021-11-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20211122_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='suspendDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
