# Generated by Django 3.2.8 on 2021-11-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
    ]
